name: kanban_board
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  csv: ^5.0.1
  uuid: ^3.0.7
  rive: ^0.9.1
  intl: ^0.17.0
  provider: ^6.0.4
  flutter_svg: ^1.1.6
  firebase_core: ^2.4.0
  flutter_share: ^2.0.0
  firebase_auth: ^4.2.1
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  json_serializable: ^6.5.4
  firebase_database: ^10.0.8
  firebase_analytics: ^10.0.7
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3
  firebase_crashlytics: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/image/